// Code generated by "requestgen -method GET -url /wapi/v1/history/fills -type GetFillHistoryRequest -responseType []OrderFill -rateLimiter 1+30/60s"; DO NOT EDIT.

package backpackapi

import (
	"context"
	"encoding/json"
	"fmt"
	"golang.org/x/time/rate"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"sync"
	"time"
)

var GetFillHistoryRequestLimiter = rate.NewLimiter(0.5, 1)

/*
 * Symbol sets
 */
func (g *GetFillHistoryRequest) Symbol(symbol string) *GetFillHistoryRequest {
	g.symbol = &symbol
	return g
}

/*
 * OrderId sets
 */
func (g *GetFillHistoryRequest) OrderId(orderId string) *GetFillHistoryRequest {
	g.orderId = &orderId
	return g
}

/*
 * StrategyId sets
 */
func (g *GetFillHistoryRequest) StrategyId(strategyId string) *GetFillHistoryRequest {
	g.strategyId = &strategyId
	return g
}

/*
 * MarketType sets
 */
func (g *GetFillHistoryRequest) MarketType(marketType MarketType) *GetFillHistoryRequest {
	g.marketType = &marketType
	return g
}

/*
 * From sets from is inclusive and to is exclusive.
 */
func (g *GetFillHistoryRequest) From(from time.Time) *GetFillHistoryRequest {
	g.from = &from
	return g
}

/*
 * To sets
 */
func (g *GetFillHistoryRequest) To(to time.Time) *GetFillHistoryRequest {
	g.to = &to
	return g
}

/*
 * FillType sets
 */
func (g *GetFillHistoryRequest) FillType(fillType FillType) *GetFillHistoryRequest {
	g.fillType = &fillType
	return g
}

/*
 * Limit sets limit defaults to 100 and is capped at 1000.
 */
func (g *GetFillHistoryRequest) Limit(limit uint64) *GetFillHistoryRequest {
	g.limit = &limit
	return g
}

/*
 * Offset sets
 */
func (g *GetFillHistoryRequest) Offset(offset uint64) *GetFillHistoryRequest {
	g.offset = &offset
	return g
}

/*
 * SortDirection sets
 */
func (g *GetFillHistoryRequest) SortDirection(sortDirection SortDirection) *GetFillHistoryRequest {
	g.sortDirection = &sortDirection
	return g
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (g *GetFillHistoryRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}

	query := url.Values{}
	for _k, _v := range params {
		if g.isVarSlice(_v) {
			g.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (g *GetFillHistoryRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check symbol field -> json key symbol
	if g.symbol != nil {
		symbol := *g.symbol

		// TEMPLATE check-required
		if len(symbol) == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of symbol
		params["symbol"] = symbol
	} else {
	}
	// check orderId field -> json key orderId
	if g.orderId != nil {
		orderId := *g.orderId

		// TEMPLATE check-required
		if len(orderId) == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of orderId
		params["orderId"] = orderId
	} else {
	}
	// check strategyId field -> json key strategyId
	if g.strategyId != nil {
		strategyId := *g.strategyId

		// TEMPLATE check-required
		if len(strategyId) == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of strategyId
		params["strategyId"] = strategyId
	} else {
	}
	// check marketType field -> json key marketType
	if g.marketType != nil {
		marketType := *g.marketType

		// TEMPLATE check-required
		if len(marketType) == 0 {
		}
		// END TEMPLATE check-required

		// TEMPLATE check-valid-values
		switch marketType {
		case MarketTypeSpot, MarketTypePerp, MarketTypeIPerp, MarketTypeDated, MarketTypePrediction, MarketTypeRfq:
			params["marketType"] = marketType

		default:
			return nil, fmt.Errorf("marketType value %v is invalid", marketType)

		}
		// END TEMPLATE check-valid-values

		// assign parameter of marketType
		params["marketType"] = marketType
	} else {
	}
	// check from field -> json key from
	if g.from != nil {
		from := *g.from

		// TEMPLATE check-required

		if from.IsZero() {
		}
		// END TEMPLATE check-required

		// assign parameter of from
		// convert time.Time to milliseconds time stamp
		params["from"] = strconv.FormatInt(from.UnixNano()/int64(time.Millisecond), 10)
	} else {
	}
	// check to field -> json key to
	if g.to != nil {
		to := *g.to

		// TEMPLATE check-required

		if to.IsZero() {
		}
		// END TEMPLATE check-required

		// assign parameter of to
		// convert time.Time to milliseconds time stamp
		params["to"] = strconv.FormatInt(to.UnixNano()/int64(time.Millisecond), 10)
	} else {
	}
	// check fillType field -> json key fillType
	if g.fillType != nil {
		fillType := *g.fillType

		// TEMPLATE check-required
		if len(fillType) == 0 {
		}
		// END TEMPLATE check-required

		// TEMPLATE check-valid-values
		switch fillType {
		case FillTypeUser, FillTypeBookLiquidation, FillTypeAdl, FillTypeBackstop, FillTypeLiquidation, FillTypeAllLiquidation, FillTypeCollateralConversion, FillTypeCollateralConversionAndSpotLiquidation:
			params["fillType"] = fillType

		default:
			return nil, fmt.Errorf("fillType value %v is invalid", fillType)

		}
		// END TEMPLATE check-valid-values

		// assign parameter of fillType
		params["fillType"] = fillType
	} else {
	}
	// check limit field -> json key limit
	if g.limit != nil {
		limit := *g.limit

		// TEMPLATE check-required
		// END TEMPLATE check-required

		// assign parameter of limit
		params["limit"] = limit
	} else {
	}
	// check offset field -> json key offset
	if g.offset != nil {
		offset := *g.offset

		// TEMPLATE check-required
		// END TEMPLATE check-required

		// assign parameter of offset
		params["offset"] = offset
	} else {
	}
	// check sortDirection field -> json key sortDirection
	if g.sortDirection != nil {
		sortDirection := *g.sortDirection

		// TEMPLATE check-required
		if len(sortDirection) == 0 {
		}
		// END TEMPLATE check-required

		// TEMPLATE check-valid-values
		switch sortDirection {
		case SortDirectionAsc, SortDirectionDesc:
			params["sortDirection"] = sortDirection

		default:
			return nil, fmt.Errorf("sortDirection value %v is invalid", sortDirection)

		}
		// END TEMPLATE check-valid-values

		// assign parameter of sortDirection
		params["sortDirection"] = sortDirection
	} else {
	}

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (g *GetFillHistoryRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := g.GetParameters()
	if err != nil {
		return query, err
	}

	for _k, _v := range params {
		if g.isVarSlice(_v) {
			g.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (g *GetFillHistoryRequest) GetParametersJSON() ([]byte, error) {
	params, err := g.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (g *GetFillHistoryRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}

	return params, nil
}

var GetFillHistoryRequestSlugReCache sync.Map

func (g *GetFillHistoryRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for _k, _v := range slugs {
		var needleRE *regexp.Regexp

		if cached, ok := GetFillHistoryRequestSlugReCache.Load(_k); ok {
			needleRE = cached.(*regexp.Regexp)
		} else {
			needleRE = regexp.MustCompile(":" + _k + "\\b")
			GetFillHistoryRequestSlugReCache.Store(_k, needleRE)
		}

		url = needleRE.ReplaceAllString(url, _v)
	}

	return url
}

func (g *GetFillHistoryRequest) iterateSlice(slice interface{}, _f func(it interface{})) {
	sliceValue := reflect.ValueOf(slice)
	for _i := 0; _i < sliceValue.Len(); _i++ {
		it := sliceValue.Index(_i).Interface()
		_f(it)
	}
}

func (g *GetFillHistoryRequest) isVarSlice(_v interface{}) bool {
	rt := reflect.TypeOf(_v)
	switch rt.Kind() {
	case reflect.Slice:
		return true
	}
	return false
}

func (g *GetFillHistoryRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := g.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for _k, _v := range params {
		slugs[_k] = fmt.Sprintf("%v", _v)
	}

	return slugs, nil
}

// GetPath returns the request path of the API
func (g *GetFillHistoryRequest) GetPath() string {
	return "/wapi/v1/history/fills"
}

// Do generates the request object and send the request object to the API endpoint
func (g *GetFillHistoryRequest) Do(ctx context.Context) ([]OrderFill, error) {
	if err := GetFillHistoryRequestLimiter.Wait(ctx); err != nil {
		return nil, err
	}

	// empty params for GET operation
	var params interface{}
	query, err := g.GetParametersQuery()
	if err != nil {
		return nil, err
	}

	var apiURL string

	apiURL = g.GetPath()

	req, err := g.client.NewAuthenticatedRequest(ctx, "GET", apiURL, query, params)
	if err != nil {
		return nil, err
	}

	response, err := g.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse []OrderFill

	type responseUnmarshaler interface {
		Unmarshal(data []byte) error
	}

	if unmarshaler, ok := interface{}(&apiResponse).(responseUnmarshaler); ok {
		if err := unmarshaler.Unmarshal(response.Body); err != nil {
			return nil, err
		}
	} else {
		// The line below checks the content type, however, some API server might not send the correct content type header,
		// Hence, this is commented for backward compatibility
		// response.IsJSON()
		if err := response.DecodeJSON(&apiResponse); err != nil {
			return nil, err
		}
	}

	type responseValidator interface {
		Validate() error
	}

	if validator, ok := interface{}(&apiResponse).(responseValidator); ok {
		if err := validator.Validate(); err != nil {
			return nil, err
		}
	}
	return apiResponse, nil
}
