// Code generated by "callbackgen -type ExchangeSession"; DO NOT EDIT.

package bbgo

import (
	"github.com/c9s/bbgo/pkg/fixedpoint"
)

func (session *ExchangeSession) OnMaxBorrowable(cb func(asset string, amount fixedpoint.Value)) {
	session.maxBorrowableCallbacks = append(session.maxBorrowableCallbacks, cb)
}

func (session *ExchangeSession) EmitMaxBorrowable(asset string, amount fixedpoint.Value) {
	for _, cb := range session.maxBorrowableCallbacks {
		cb(asset, amount)
	}
}
