// Code generated by "callbackgen -type StrategyController strategy_controller.go"; DO NOT EDIT.

package bbgo

import ()

func (s *StrategyController) OnSuspend(cb func()) {
	s.SuspendCallbacks = append(s.SuspendCallbacks, cb)
}

func (s *StrategyController) EmitSuspend() {
	for _, cb := range s.SuspendCallbacks {
		cb()
	}
}

func (s *StrategyController) OnResume(cb func()) {
	s.ResumeCallbacks = append(s.ResumeCallbacks, cb)
}

func (s *StrategyController) EmitResume() {
	for _, cb := range s.ResumeCallbacks {
		cb()
	}
}

func (s *StrategyController) OnEmergencyStop(cb func()) {
	s.EmergencyStopCallbacks = append(s.EmergencyStopCallbacks, cb)
}

func (s *StrategyController) EmitEmergencyStop() {
	for _, cb := range s.EmergencyStopCallbacks {
		cb()
	}
}
