// Code generated by "requestgen -method GET -url /api/v3/wallet/:walletType/orders -type V3CreateOrderRequest -responseType .Order"; DO NOT EDIT.

package max

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
)

func (v *V3CreateOrderRequest) Market(market string) *V3CreateOrderRequest {
	v.market = market
	return v
}

func (v *V3CreateOrderRequest) Side(side string) *V3CreateOrderRequest {
	v.side = side
	return v
}

func (v *V3CreateOrderRequest) Volume(volume string) *V3CreateOrderRequest {
	v.volume = volume
	return v
}

func (v *V3CreateOrderRequest) OrderType(orderType string) *V3CreateOrderRequest {
	v.orderType = orderType
	return v
}

func (v *V3CreateOrderRequest) Price(price string) *V3CreateOrderRequest {
	v.price = &price
	return v
}

func (v *V3CreateOrderRequest) StopPrice(stopPrice string) *V3CreateOrderRequest {
	v.stopPrice = &stopPrice
	return v
}

func (v *V3CreateOrderRequest) ClientOrderID(clientOrderID string) *V3CreateOrderRequest {
	v.clientOrderID = &clientOrderID
	return v
}

func (v *V3CreateOrderRequest) GroupID(groupID string) *V3CreateOrderRequest {
	v.groupID = &groupID
	return v
}

func (v *V3CreateOrderRequest) WalletType(walletType string) *V3CreateOrderRequest {
	v.walletType = walletType
	return v
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (v *V3CreateOrderRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}

	query := url.Values{}
	for _k, _v := range params {
		query.Add(_k, fmt.Sprintf("%v", _v))
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (v *V3CreateOrderRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check market field -> json key market
	market := v.market

	// TEMPLATE check-required
	if len(market) == 0 {
		return nil, fmt.Errorf("market is required, empty string given")
	}
	// END TEMPLATE check-required

	// assign parameter of market
	params["market"] = market
	// check side field -> json key side
	side := v.side

	// TEMPLATE check-required
	if len(side) == 0 {
		return nil, fmt.Errorf("side is required, empty string given")
	}
	// END TEMPLATE check-required

	// assign parameter of side
	params["side"] = side
	// check volume field -> json key volume
	volume := v.volume

	// TEMPLATE check-required
	if len(volume) == 0 {
		return nil, fmt.Errorf("volume is required, empty string given")
	}
	// END TEMPLATE check-required

	// assign parameter of volume
	params["volume"] = volume
	// check orderType field -> json key ord_type
	orderType := v.orderType

	// assign parameter of orderType
	params["ord_type"] = orderType
	// check price field -> json key price
	if v.price != nil {
		price := *v.price

		// assign parameter of price
		params["price"] = price
	} else {
	}
	// check stopPrice field -> json key stop_price
	if v.stopPrice != nil {
		stopPrice := *v.stopPrice

		// assign parameter of stopPrice
		params["stop_price"] = stopPrice
	} else {
	}
	// check clientOrderID field -> json key client_oid
	if v.clientOrderID != nil {
		clientOrderID := *v.clientOrderID

		// assign parameter of clientOrderID
		params["client_oid"] = clientOrderID
	} else {
	}
	// check groupID field -> json key group_id
	if v.groupID != nil {
		groupID := *v.groupID

		// assign parameter of groupID
		params["group_id"] = groupID
	} else {
	}

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (v *V3CreateOrderRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := v.GetParameters()
	if err != nil {
		return query, err
	}

	for _k, _v := range params {
		if v.isVarSlice(_v) {
			v.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (v *V3CreateOrderRequest) GetParametersJSON() ([]byte, error) {
	params, err := v.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (v *V3CreateOrderRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check walletType field -> json key walletType
	walletType := v.walletType

	// TEMPLATE check-required
	if len(walletType) == 0 {
		return nil, fmt.Errorf("walletType is required, empty string given")
	}
	// END TEMPLATE check-required

	// assign parameter of walletType
	params["walletType"] = walletType

	return params, nil
}

func (v *V3CreateOrderRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for _k, _v := range slugs {
		needleRE := regexp.MustCompile(":" + _k + "\\b")
		url = needleRE.ReplaceAllString(url, _v)
	}

	return url
}

func (v *V3CreateOrderRequest) iterateSlice(slice interface{}, _f func(it interface{})) {
	sliceValue := reflect.ValueOf(slice)
	for _i := 0; _i < sliceValue.Len(); _i++ {
		it := sliceValue.Index(_i).Interface()
		_f(it)
	}
}

func (v *V3CreateOrderRequest) isVarSlice(_v interface{}) bool {
	rt := reflect.TypeOf(_v)
	switch rt.Kind() {
	case reflect.Slice:
		return true
	}
	return false
}

func (v *V3CreateOrderRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := v.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for _k, _v := range params {
		slugs[_k] = fmt.Sprintf("%v", _v)
	}

	return slugs, nil
}

func (v *V3CreateOrderRequest) Do(ctx context.Context) (*Order, error) {

	// empty params for GET operation
	var params interface{}
	query, err := v.GetParametersQuery()
	if err != nil {
		return nil, err
	}

	apiURL := "/api/v3/wallet/:walletType/orders"
	slugs, err := v.GetSlugsMap()
	if err != nil {
		return nil, err
	}

	apiURL = v.applySlugsToUrl(apiURL, slugs)

	req, err := v.client.NewAuthenticatedRequest(ctx, "GET", apiURL, query, params)
	if err != nil {
		return nil, err
	}

	response, err := v.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse Order
	if err := response.DecodeJSON(&apiResponse); err != nil {
		return nil, err
	}
	return &apiResponse, nil
}
