// Code generated by "requestgen -type CancelAllOrderRequest"; DO NOT EDIT.

package kucoinapi

import (
	"encoding/json"
	"fmt"
	"net/url"
)

func (r *CancelAllOrderRequest) Symbol(symbol string) *CancelAllOrderRequest {
	r.symbol = &symbol
	return r
}

func (r *CancelAllOrderRequest) TradeType(tradeType string) *CancelAllOrderRequest {
	r.tradeType = &tradeType
	return r
}

func (r *CancelAllOrderRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}

	// check symbol field -> json key symbol
	if r.symbol != nil {
		symbol := *r.symbol

		// assign parameter of symbol
		params["symbol"] = symbol
	}

	// check tradeType field -> json key tradeType
	if r.tradeType != nil {
		tradeType := *r.tradeType

		// assign parameter of tradeType
		params["tradeType"] = tradeType
	}

	return params, nil
}

func (r *CancelAllOrderRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := r.GetParameters()
	if err != nil {
		return query, err
	}

	for k, v := range params {
		query.Add(k, fmt.Sprintf("%v", v))
	}

	return query, nil
}

func (r *CancelAllOrderRequest) GetParametersJSON() ([]byte, error) {
	params, err := r.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}
