// Code generated by "requestgen -method GET -responseType .APIResponse -responseDataField Data -url /api/v1/accounts/:accountID -type NewGetAccountRequest -responseDataType .Account"; DO NOT EDIT.

package kucoinapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"regexp"
)

func (n *NewGetAccountRequest) AccountID(accountID string) *NewGetAccountRequest {
	n.accountID = accountID
	return n
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (n *NewGetAccountRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}

	query := url.Values{}
	for k, v := range params {
		query.Add(k, fmt.Sprintf("%v", v))
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (n *NewGetAccountRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (n *NewGetAccountRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := n.GetParameters()
	if err != nil {
		return query, err
	}

	for k, v := range params {
		query.Add(k, fmt.Sprintf("%v", v))
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (n *NewGetAccountRequest) GetParametersJSON() ([]byte, error) {
	params, err := n.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (n *NewGetAccountRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check accountID field -> json key accountID
	accountID := n.accountID

	// assign parameter of accountID
	params["accountID"] = accountID

	return params, nil
}

func (n *NewGetAccountRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for k, v := range slugs {
		needleRE := regexp.MustCompile(":" + k + "\\b")
		url = needleRE.ReplaceAllString(url, v)
	}

	return url
}

func (n *NewGetAccountRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := n.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for k, v := range params {
		slugs[k] = fmt.Sprintf("%v", v)
	}

	return slugs, nil
}

func (n *NewGetAccountRequest) Do(ctx context.Context) (*Account, error) {

	// no body params
	var params interface{}
	query := url.Values{}

	apiURL := "/api/v1/accounts/:accountID"
	slugs, err := n.GetSlugsMap()
	if err != nil {
		return nil, err
	}

	apiURL = n.applySlugsToUrl(apiURL, slugs)

	req, err := n.client.NewAuthenticatedRequest(ctx, "GET", apiURL, query, params)
	if err != nil {
		return nil, err
	}

	response, err := n.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse APIResponse
	if err := response.DecodeJSON(&apiResponse); err != nil {
		return nil, err
	}
	var data Account
	if err := json.Unmarshal(apiResponse.Data, &data); err != nil {
		return nil, err
	}
	return &data, nil
}
