// Code generated by "requestgen -method GET -url /api/v3/withdrawals -type GetWithdrawalHistoryRequest -responseType []Withdrawal"; DO NOT EDIT.

package v3

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"sync"
	"time"
)

/*
 * Currency sets
 */
func (g *GetWithdrawalHistoryRequest) Currency(currency string) *GetWithdrawalHistoryRequest {
	g.currency = &currency
	return g
}

/*
 * State sets
 */
func (g *GetWithdrawalHistoryRequest) State(state WithdrawState) *GetWithdrawalHistoryRequest {
	g.state = &state
	return g
}

/*
 * Timestamp sets
 */
func (g *GetWithdrawalHistoryRequest) Timestamp(timestamp time.Time) *GetWithdrawalHistoryRequest {
	g.timestamp = &timestamp
	return g
}

/*
 * Order sets order could be desc or asc
 */
func (g *GetWithdrawalHistoryRequest) Order(order string) *GetWithdrawalHistoryRequest {
	g.order = &order
	return g
}

/*
 * Limit sets limit's default = 50
 */
func (g *GetWithdrawalHistoryRequest) Limit(limit int) *GetWithdrawalHistoryRequest {
	g.limit = &limit
	return g
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (g *GetWithdrawalHistoryRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}

	query := url.Values{}
	for _k, _v := range params {
		if g.isVarSlice(_v) {
			g.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (g *GetWithdrawalHistoryRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check currency field -> json key currency
	if g.currency != nil {
		currency := *g.currency

		// TEMPLATE check-required
		if len(currency) == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of currency
		params["currency"] = currency
	} else {
	}
	// check state field -> json key state
	if g.state != nil {
		state := *g.state

		// TEMPLATE check-required
		if len(state) == 0 {
		}
		// END TEMPLATE check-required

		// TEMPLATE check-valid-values
		switch state {
		case WithdrawStateProcessing, WithdrawStateFailed, WithdrawStateCanceled, WithdrawStateDone:
			params["state"] = state

		default:
			return nil, fmt.Errorf("state value %v is invalid", state)

		}
		// END TEMPLATE check-valid-values

		// assign parameter of state
		params["state"] = state
	} else {
	}
	// check timestamp field -> json key timestamp
	if g.timestamp != nil {
		timestamp := *g.timestamp

		// TEMPLATE check-required

		if timestamp.IsZero() {
		}
		// END TEMPLATE check-required

		// assign parameter of timestamp
		// convert time.Time to milliseconds time stamp
		params["timestamp"] = strconv.FormatInt(timestamp.UnixNano()/int64(time.Millisecond), 10)
	} else {
	}
	// check order field -> json key order
	if g.order != nil {
		order := *g.order

		// TEMPLATE check-required
		if len(order) == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of order
		params["order"] = order
	} else {
	}
	// check limit field -> json key limit
	if g.limit != nil {
		limit := *g.limit

		// TEMPLATE check-required

		if limit == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of limit
		params["limit"] = limit
	} else {
	}

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (g *GetWithdrawalHistoryRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := g.GetParameters()
	if err != nil {
		return query, err
	}

	for _k, _v := range params {
		if g.isVarSlice(_v) {
			g.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (g *GetWithdrawalHistoryRequest) GetParametersJSON() ([]byte, error) {
	params, err := g.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (g *GetWithdrawalHistoryRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}

	return params, nil
}

var GetWithdrawalHistoryRequestSlugReCache sync.Map

func (g *GetWithdrawalHistoryRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for _k, _v := range slugs {
		var needleRE *regexp.Regexp

		if cached, ok := GetWithdrawalHistoryRequestSlugReCache.Load(_k); ok {
			needleRE = cached.(*regexp.Regexp)
		} else {
			needleRE = regexp.MustCompile(":" + _k + "\\b")
			GetWithdrawalHistoryRequestSlugReCache.Store(_k, needleRE)
		}

		url = needleRE.ReplaceAllString(url, _v)
	}

	return url
}

func (g *GetWithdrawalHistoryRequest) iterateSlice(slice interface{}, _f func(it interface{})) {
	sliceValue := reflect.ValueOf(slice)
	for _i := 0; _i < sliceValue.Len(); _i++ {
		it := sliceValue.Index(_i).Interface()
		_f(it)
	}
}

func (g *GetWithdrawalHistoryRequest) isVarSlice(_v interface{}) bool {
	rt := reflect.TypeOf(_v)
	switch rt.Kind() {
	case reflect.Slice:
		return true
	}
	return false
}

func (g *GetWithdrawalHistoryRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := g.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for _k, _v := range params {
		slugs[_k] = fmt.Sprintf("%v", _v)
	}

	return slugs, nil
}

// GetPath returns the request path of the API
func (g *GetWithdrawalHistoryRequest) GetPath() string {
	return "/api/v3/withdrawals"
}

// Do generates the request object and send the request object to the API endpoint
func (g *GetWithdrawalHistoryRequest) Do(ctx context.Context) ([]Withdrawal, error) {

	// empty params for GET operation
	var params interface{}
	query, err := g.GetParametersQuery()
	if err != nil {
		return nil, err
	}

	var apiURL string

	apiURL = g.GetPath()

	req, err := g.client.NewAuthenticatedRequest(ctx, "GET", apiURL, query, params)
	if err != nil {
		return nil, err
	}

	response, err := g.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse []Withdrawal

	type responseUnmarshaler interface {
		Unmarshal(data []byte) error
	}

	if unmarshaler, ok := interface{}(&apiResponse).(responseUnmarshaler); ok {
		if err := unmarshaler.Unmarshal(response.Body); err != nil {
			return nil, err
		}
	} else {
		// The line below checks the content type, however, some API server might not send the correct content type header,
		// Hence, this is commented for backward compatibility
		// response.IsJSON()
		if err := response.DecodeJSON(&apiResponse); err != nil {
			return nil, err
		}
	}

	type responseValidator interface {
		Validate() error
	}

	if validator, ok := interface{}(&apiResponse).(responseValidator); ok {
		if err := validator.Validate(); err != nil {
			return nil, err
		}
	}
	return apiResponse, nil
}
