// Code generated by "requestgen -method DELETE -url /api/v3/wallet/:walletType/orders -type OrderCancelAllRequest -responseType []Order"; DO NOT EDIT.

package v3

import (
	"context"
	"encoding/json"
	"fmt"
	"github.com/c9s/bbgo/pkg/exchange/max/maxapi"
	"net/url"
	"reflect"
	"regexp"
)

func (o *OrderCancelAllRequest) Side(side string) *OrderCancelAllRequest {
	o.side = &side
	return o
}

func (o *OrderCancelAllRequest) Market(market string) *OrderCancelAllRequest {
	o.market = &market
	return o
}

func (o *OrderCancelAllRequest) GroupID(groupID uint32) *OrderCancelAllRequest {
	o.groupID = &groupID
	return o
}

func (o *OrderCancelAllRequest) WalletType(walletType string) *OrderCancelAllRequest {
	o.walletType = walletType
	return o
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (o *OrderCancelAllRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}

	query := url.Values{}
	for _k, _v := range params {
		query.Add(_k, fmt.Sprintf("%v", _v))
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (o *OrderCancelAllRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check side field -> json key side
	if o.side != nil {
		side := *o.side

		// assign parameter of side
		params["side"] = side
	} else {
	}
	// check market field -> json key market
	if o.market != nil {
		market := *o.market

		// assign parameter of market
		params["market"] = market
	} else {
	}
	// check groupID field -> json key groupID
	if o.groupID != nil {
		groupID := *o.groupID

		// assign parameter of groupID
		params["groupID"] = groupID
	} else {
	}

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (o *OrderCancelAllRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := o.GetParameters()
	if err != nil {
		return query, err
	}

	for _k, _v := range params {
		if o.isVarSlice(_v) {
			o.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (o *OrderCancelAllRequest) GetParametersJSON() ([]byte, error) {
	params, err := o.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (o *OrderCancelAllRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check walletType field -> json key walletType
	walletType := o.walletType

	// TEMPLATE check-required
	if len(walletType) == 0 {
		return nil, fmt.Errorf("walletType is required, empty string given")
	}
	// END TEMPLATE check-required

	// assign parameter of walletType
	params["walletType"] = walletType

	return params, nil
}

func (o *OrderCancelAllRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for _k, _v := range slugs {
		needleRE := regexp.MustCompile(":" + _k + "\\b")
		url = needleRE.ReplaceAllString(url, _v)
	}

	return url
}

func (o *OrderCancelAllRequest) iterateSlice(slice interface{}, _f func(it interface{})) {
	sliceValue := reflect.ValueOf(slice)
	for _i := 0; _i < sliceValue.Len(); _i++ {
		it := sliceValue.Index(_i).Interface()
		_f(it)
	}
}

func (o *OrderCancelAllRequest) isVarSlice(_v interface{}) bool {
	rt := reflect.TypeOf(_v)
	switch rt.Kind() {
	case reflect.Slice:
		return true
	}
	return false
}

func (o *OrderCancelAllRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := o.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for _k, _v := range params {
		slugs[_k] = fmt.Sprintf("%v", _v)
	}

	return slugs, nil
}

func (o *OrderCancelAllRequest) Do(ctx context.Context) ([]max.Order, error) {

	params, err := o.GetParameters()
	if err != nil {
		return nil, err
	}
	query := url.Values{}

	apiURL := "/api/v3/wallet/:walletType/orders"
	slugs, err := o.GetSlugsMap()
	if err != nil {
		return nil, err
	}

	apiURL = o.applySlugsToUrl(apiURL, slugs)

	req, err := o.client.NewAuthenticatedRequest(ctx, "DELETE", apiURL, query, params)
	if err != nil {
		return nil, err
	}

	response, err := o.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse []max.Order
	if err := response.DecodeJSON(&apiResponse); err != nil {
		return nil, err
	}
	return apiResponse, nil
}
