// Code generated by "requestgen -method POST -url /fapi/v1/feeBurn -type FuturesToggleBnbBurnRequest -responseType FuturesToggleBnbBurnResponse"; DO NOT EDIT.

package binanceapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
	"sync"
)

/*
 * SetFeeBurn sets
 */
func (f *FuturesToggleBnbBurnRequest) SetFeeBurn(FeeBurn string) *FuturesToggleBnbBurnRequest {
	f.FeeBurn = FeeBurn
	return f
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (f *FuturesToggleBnbBurnRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}

	query := url.Values{}
	for _k, _v := range params {
		if f.isVarSlice(_v) {
			f.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (f *FuturesToggleBnbBurnRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check FeeBurn field -> json key feeBurn
	FeeBurn := f.FeeBurn

	// TEMPLATE check-required
	if len(FeeBurn) == 0 {
	}
	// END TEMPLATE check-required

	// assign parameter of FeeBurn
	params["feeBurn"] = FeeBurn

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (f *FuturesToggleBnbBurnRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := f.GetParameters()
	if err != nil {
		return query, err
	}

	for _k, _v := range params {
		if f.isVarSlice(_v) {
			f.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (f *FuturesToggleBnbBurnRequest) GetParametersJSON() ([]byte, error) {
	params, err := f.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (f *FuturesToggleBnbBurnRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}

	return params, nil
}

var FuturesToggleBnbBurnRequestSlugReCache sync.Map

func (f *FuturesToggleBnbBurnRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for _k, _v := range slugs {
		var needleRE *regexp.Regexp

		if cached, ok := FuturesToggleBnbBurnRequestSlugReCache.Load(_k); ok {
			needleRE = cached.(*regexp.Regexp)
		} else {
			needleRE = regexp.MustCompile(":" + _k + "\\b")
			FuturesToggleBnbBurnRequestSlugReCache.Store(_k, needleRE)
		}

		url = needleRE.ReplaceAllString(url, _v)
	}

	return url
}

func (f *FuturesToggleBnbBurnRequest) iterateSlice(slice interface{}, _f func(it interface{})) {
	sliceValue := reflect.ValueOf(slice)
	for _i := 0; _i < sliceValue.Len(); _i++ {
		it := sliceValue.Index(_i).Interface()
		_f(it)
	}
}

func (f *FuturesToggleBnbBurnRequest) isVarSlice(_v interface{}) bool {
	rt := reflect.TypeOf(_v)
	switch rt.Kind() {
	case reflect.Slice:
		return true
	}
	return false
}

func (f *FuturesToggleBnbBurnRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := f.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for _k, _v := range params {
		slugs[_k] = fmt.Sprintf("%v", _v)
	}

	return slugs, nil
}

// GetPath returns the request path of the API
func (f *FuturesToggleBnbBurnRequest) GetPath() string {
	return "/fapi/v1/feeBurn"
}

// Do generates the request object and send the request object to the API endpoint
func (f *FuturesToggleBnbBurnRequest) Do(ctx context.Context) (*FuturesToggleBnbBurnResponse, error) {

	params, err := f.GetParameters()
	if err != nil {
		return nil, err
	}
	query := url.Values{}

	var apiURL string

	apiURL = f.GetPath()

	req, err := f.client.NewAuthenticatedRequest(ctx, "POST", apiURL, query, params)
	if err != nil {
		return nil, err
	}

	response, err := f.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse FuturesToggleBnbBurnResponse

	type responseUnmarshaler interface {
		Unmarshal(data []byte) error
	}

	if unmarshaler, ok := interface{}(&apiResponse).(responseUnmarshaler); ok {
		if err := unmarshaler.Unmarshal(response.Body); err != nil {
			return nil, err
		}
	} else {
		// The line below checks the content type, however, some API server might not send the correct content type header,
		// Hence, this is commented for backward compatibility
		// response.IsJSON()
		if err := response.DecodeJSON(&apiResponse); err != nil {
			return nil, err
		}
	}

	type responseValidator interface {
		Validate() error
	}

	if validator, ok := interface{}(&apiResponse).(responseValidator); ok {
		if err := validator.Validate(); err != nil {
			return nil, err
		}
	}
	return &apiResponse, nil
}
