// Code generated by "requestgen -method GET -url /sapi/v1/margin/borrow-repay -type GetMarginBorrowRepayHistoryRequest -responseType .RowsResponse -responseDataField Rows -responseDataType []MarginBorrowRepayRecord"; DO NOT EDIT.

package binanceapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
	"strconv"
	"time"
)

func (g *GetMarginBorrowRepayHistoryRequest) Asset(asset string) *GetMarginBorrowRepayHistoryRequest {
	g.asset = asset
	return g
}

func (g *GetMarginBorrowRepayHistoryRequest) StartTime(startTime time.Time) *GetMarginBorrowRepayHistoryRequest {
	g.startTime = &startTime
	return g
}

func (g *GetMarginBorrowRepayHistoryRequest) EndTime(endTime time.Time) *GetMarginBorrowRepayHistoryRequest {
	g.endTime = &endTime
	return g
}

func (g *GetMarginBorrowRepayHistoryRequest) IsolatedSymbol(isolatedSymbol string) *GetMarginBorrowRepayHistoryRequest {
	g.isolatedSymbol = &isolatedSymbol
	return g
}

func (g *GetMarginBorrowRepayHistoryRequest) Archived(archived bool) *GetMarginBorrowRepayHistoryRequest {
	g.archived = &archived
	return g
}

func (g *GetMarginBorrowRepayHistoryRequest) Size(size int) *GetMarginBorrowRepayHistoryRequest {
	g.size = &size
	return g
}

func (g *GetMarginBorrowRepayHistoryRequest) Current(current int) *GetMarginBorrowRepayHistoryRequest {
	g.current = &current
	return g
}

func (g *GetMarginBorrowRepayHistoryRequest) SetBorrowRepayType(BorrowRepayType BorrowRepayType) *GetMarginBorrowRepayHistoryRequest {
	g.BorrowRepayType = BorrowRepayType
	return g
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (g *GetMarginBorrowRepayHistoryRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}

	query := url.Values{}
	for _k, _v := range params {
		query.Add(_k, fmt.Sprintf("%v", _v))
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (g *GetMarginBorrowRepayHistoryRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check asset field -> json key asset
	asset := g.asset

	// assign parameter of asset
	params["asset"] = asset
	// check startTime field -> json key startTime
	if g.startTime != nil {
		startTime := *g.startTime

		// assign parameter of startTime
		// convert time.Time to milliseconds time stamp
		params["startTime"] = strconv.FormatInt(startTime.UnixNano()/int64(time.Millisecond), 10)
	} else {
	}
	// check endTime field -> json key endTime
	if g.endTime != nil {
		endTime := *g.endTime

		// assign parameter of endTime
		// convert time.Time to milliseconds time stamp
		params["endTime"] = strconv.FormatInt(endTime.UnixNano()/int64(time.Millisecond), 10)
	} else {
	}
	// check isolatedSymbol field -> json key isolatedSymbol
	if g.isolatedSymbol != nil {
		isolatedSymbol := *g.isolatedSymbol

		// assign parameter of isolatedSymbol
		params["isolatedSymbol"] = isolatedSymbol
	} else {
	}
	// check archived field -> json key archived
	if g.archived != nil {
		archived := *g.archived

		// assign parameter of archived
		params["archived"] = archived
	} else {
	}
	// check size field -> json key size
	if g.size != nil {
		size := *g.size

		// assign parameter of size
		params["size"] = size
	} else {
	}
	// check current field -> json key current
	if g.current != nil {
		current := *g.current

		// assign parameter of current
		params["current"] = current
	} else {
	}
	// check BorrowRepayType field -> json key type
	BorrowRepayType := g.BorrowRepayType

	// TEMPLATE check-valid-values
	switch BorrowRepayType {
	case BorrowRepayTypeBorrow, BorrowRepayTypeRepay:
		params["type"] = BorrowRepayType

	default:
		return nil, fmt.Errorf("type value %v is invalid", BorrowRepayType)

	}
	// END TEMPLATE check-valid-values

	// assign parameter of BorrowRepayType
	params["type"] = BorrowRepayType

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (g *GetMarginBorrowRepayHistoryRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := g.GetParameters()
	if err != nil {
		return query, err
	}

	for _k, _v := range params {
		if g.isVarSlice(_v) {
			g.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (g *GetMarginBorrowRepayHistoryRequest) GetParametersJSON() ([]byte, error) {
	params, err := g.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (g *GetMarginBorrowRepayHistoryRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}

	return params, nil
}

func (g *GetMarginBorrowRepayHistoryRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for _k, _v := range slugs {
		needleRE := regexp.MustCompile(":" + _k + "\\b")
		url = needleRE.ReplaceAllString(url, _v)
	}

	return url
}

func (g *GetMarginBorrowRepayHistoryRequest) iterateSlice(slice interface{}, _f func(it interface{})) {
	sliceValue := reflect.ValueOf(slice)
	for _i := 0; _i < sliceValue.Len(); _i++ {
		it := sliceValue.Index(_i).Interface()
		_f(it)
	}
}

func (g *GetMarginBorrowRepayHistoryRequest) isVarSlice(_v interface{}) bool {
	rt := reflect.TypeOf(_v)
	switch rt.Kind() {
	case reflect.Slice:
		return true
	}
	return false
}

func (g *GetMarginBorrowRepayHistoryRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := g.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for _k, _v := range params {
		slugs[_k] = fmt.Sprintf("%v", _v)
	}

	return slugs, nil
}

// GetPath returns the request path of the API
func (g *GetMarginBorrowRepayHistoryRequest) GetPath() string {
	return "/sapi/v1/margin/borrow-repay"
}

// Do generates the request object and send the request object to the API endpoint
func (g *GetMarginBorrowRepayHistoryRequest) Do(ctx context.Context) ([]MarginBorrowRepayRecord, error) {

	// empty params for GET operation
	var params interface{}
	query, err := g.GetParametersQuery()
	if err != nil {
		return nil, err
	}

	var apiURL string

	apiURL = g.GetPath()

	req, err := g.client.NewAuthenticatedRequest(ctx, "GET", apiURL, query, params)
	if err != nil {
		return nil, err
	}

	response, err := g.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse RowsResponse
	if err := response.DecodeJSON(&apiResponse); err != nil {
		return nil, err
	}

	type responseValidator interface {
		Validate() error
	}
	validator, ok := interface{}(apiResponse).(responseValidator)
	if ok {
		if err := validator.Validate(); err != nil {
			return nil, err
		}
	}
	var data []MarginBorrowRepayRecord
	if err := json.Unmarshal(apiResponse.Rows, &data); err != nil {
		return nil, err
	}
	return data, nil
}
