// Code generated by "requestgen -method POST -url /sapi/v1/bnbBurn -type ToggleBurnBnbRequest -responseType BurnBnbResponse"; DO NOT EDIT.

package binanceapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
	"sync"
)

/*
 * SpotBnbBurn sets
 */
func (t *ToggleBurnBnbRequest) SpotBnbBurn(spotBnbBurn bool) *ToggleBurnBnbRequest {
	t.spotBnbBurn = &spotBnbBurn
	return t
}

/*
 * InterestBnbBurn sets
 */
func (t *ToggleBurnBnbRequest) InterestBnbBurn(interestBnbBurn bool) *ToggleBurnBnbRequest {
	t.interestBnbBurn = &interestBnbBurn
	return t
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (t *ToggleBurnBnbRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}

	query := url.Values{}
	for _k, _v := range params {
		if t.isVarSlice(_v) {
			t.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (t *ToggleBurnBnbRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check spotBnbBurn field -> json key spotBNBBurn
	if t.spotBnbBurn != nil {
		spotBnbBurn := *t.spotBnbBurn

		// TEMPLATE check-required
		// END TEMPLATE check-required

		// assign parameter of spotBnbBurn
		params["spotBNBBurn"] = spotBnbBurn
	} else {
	}
	// check interestBnbBurn field -> json key interestBNBBurn
	if t.interestBnbBurn != nil {
		interestBnbBurn := *t.interestBnbBurn

		// TEMPLATE check-required
		// END TEMPLATE check-required

		// assign parameter of interestBnbBurn
		params["interestBNBBurn"] = interestBnbBurn
	} else {
	}

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (t *ToggleBurnBnbRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := t.GetParameters()
	if err != nil {
		return query, err
	}

	for _k, _v := range params {
		if t.isVarSlice(_v) {
			t.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (t *ToggleBurnBnbRequest) GetParametersJSON() ([]byte, error) {
	params, err := t.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (t *ToggleBurnBnbRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}

	return params, nil
}

var ToggleBurnBnbRequestSlugReCache sync.Map

func (t *ToggleBurnBnbRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for _k, _v := range slugs {
		var needleRE *regexp.Regexp

		if cached, ok := ToggleBurnBnbRequestSlugReCache.Load(_k); ok {
			needleRE = cached.(*regexp.Regexp)
		} else {
			needleRE = regexp.MustCompile(":" + _k + "\\b")
			ToggleBurnBnbRequestSlugReCache.Store(_k, needleRE)
		}

		url = needleRE.ReplaceAllString(url, _v)
	}

	return url
}

func (t *ToggleBurnBnbRequest) iterateSlice(slice interface{}, _f func(it interface{})) {
	sliceValue := reflect.ValueOf(slice)
	for _i := 0; _i < sliceValue.Len(); _i++ {
		it := sliceValue.Index(_i).Interface()
		_f(it)
	}
}

func (t *ToggleBurnBnbRequest) isVarSlice(_v interface{}) bool {
	rt := reflect.TypeOf(_v)
	switch rt.Kind() {
	case reflect.Slice:
		return true
	}
	return false
}

func (t *ToggleBurnBnbRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := t.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for _k, _v := range params {
		slugs[_k] = fmt.Sprintf("%v", _v)
	}

	return slugs, nil
}

// GetPath returns the request path of the API
func (t *ToggleBurnBnbRequest) GetPath() string {
	return "/sapi/v1/bnbBurn"
}

// Do generates the request object and send the request object to the API endpoint
func (t *ToggleBurnBnbRequest) Do(ctx context.Context) (*BurnBnbResponse, error) {

	params, err := t.GetParameters()
	if err != nil {
		return nil, err
	}
	query := url.Values{}

	var apiURL string

	apiURL = t.GetPath()

	req, err := t.client.NewAuthenticatedRequest(ctx, "POST", apiURL, query, params)
	if err != nil {
		return nil, err
	}

	response, err := t.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse BurnBnbResponse

	type responseUnmarshaler interface {
		Unmarshal(data []byte) error
	}

	if unmarshaler, ok := interface{}(&apiResponse).(responseUnmarshaler); ok {
		if err := unmarshaler.Unmarshal(response.Body); err != nil {
			return nil, err
		}
	} else {
		// The line below checks the content type, however, some API server might not send the correct content type header,
		// Hence, this is commented for backward compatibility
		// response.IsJSON()
		if err := response.DecodeJSON(&apiResponse); err != nil {
			return nil, err
		}
	}

	type responseValidator interface {
		Validate() error
	}

	if validator, ok := interface{}(&apiResponse).(responseValidator); ok {
		if err := validator.Validate(); err != nil {
			return nil, err
		}
	}
	return &apiResponse, nil
}
