// Code generated by "callbackgen -type Correlation"; DO NOT EDIT.

package factorzoo

import ()

func (inc *Correlation) OnUpdate(cb func(value float64)) {
	inc.UpdateCallbacks = append(inc.UpdateCallbacks, cb)
}

func (inc *Correlation) EmitUpdate(value float64) {
	for _, cb := range inc.UpdateCallbacks {
		cb(value)
	}
}
