// Code generated by "callbackgen -type MACD"; DO NOT EDIT.

package indicator

import ()

func (inc *MACD) OnUpdate(cb func(macd float64, signal float64, histogram float64)) {
	inc.updateCallbacks = append(inc.updateCallbacks, cb)
}

func (inc *MACD) EmitUpdate(macd float64, signal float64, histogram float64) {
	for _, cb := range inc.updateCallbacks {
		cb(macd, signal, histogram)
	}
}
