// Code generated by "callbackgen -type MACDLegacy"; DO NOT EDIT.

package indicator

import ()

func (inc *MACDLegacy) OnUpdate(cb func(macd float64, signal float64, histogram float64)) {
	inc.updateCallbacks = append(inc.updateCallbacks, cb)
}

func (inc *MACDLegacy) EmitUpdate(macd float64, signal float64, histogram float64) {
	for _, cb := range inc.updateCallbacks {
		cb(macd, signal, histogram)
	}
}
