// Code generated by "callbackgen -type OBV"; DO NOT EDIT.

package indicator

import ()

func (inc *OBV) OnUpdate(cb func(value float64)) {
	inc.updateCallbacks = append(inc.updateCallbacks, cb)
}

func (inc *OBV) EmitUpdate(value float64) {
	for _, cb := range inc.updateCallbacks {
		cb(value)
	}
}
