// Code generated by "requestgen -method POST -responseType .APIResponse -responseDataField Response.Data -url /info -type GetHistoricalOrdersRequest -responseDataType []HistoricalOrdersResponse"; DO NOT EDIT.

package hyperapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
)

func (g *GetHistoricalOrdersRequest) User(user string) *GetHistoricalOrdersRequest {
	g.user = user
	return g
}

func (g *GetHistoricalOrdersRequest) MetaType(metaType ReqTypeInfo) *GetHistoricalOrdersRequest {
	g.metaType = metaType
	return g
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (g *GetHistoricalOrdersRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}

	query := url.Values{}
	for _k, _v := range params {
		if g.isVarSlice(_v) {
			g.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (g *GetHistoricalOrdersRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check user field -> json key user
	user := g.user

	// TEMPLATE check-required
	if len(user) == 0 {
		return nil, fmt.Errorf("user is required, empty string given")
	}
	// END TEMPLATE check-required

	// assign parameter of user
	params["user"] = user
	// check metaType field -> json key type
	metaType := g.metaType

	// TEMPLATE check-required
	if len(metaType) == 0 {
		metaType = "historicalOrders"
	}
	// END TEMPLATE check-required

	// TEMPLATE check-valid-values
	switch metaType {
	case "historicalOrders":
		params["type"] = metaType

	default:
		return nil, fmt.Errorf("type value %v is invalid", metaType)

	}
	// END TEMPLATE check-valid-values

	// assign parameter of metaType
	params["type"] = metaType

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (g *GetHistoricalOrdersRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := g.GetParameters()
	if err != nil {
		return query, err
	}

	for _k, _v := range params {
		if g.isVarSlice(_v) {
			g.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (g *GetHistoricalOrdersRequest) GetParametersJSON() ([]byte, error) {
	params, err := g.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (g *GetHistoricalOrdersRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}

	return params, nil
}

func (g *GetHistoricalOrdersRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for _k, _v := range slugs {
		needleRE := regexp.MustCompile(":" + _k + "\\b")
		url = needleRE.ReplaceAllString(url, _v)
	}

	return url
}

func (g *GetHistoricalOrdersRequest) iterateSlice(slice interface{}, _f func(it interface{})) {
	sliceValue := reflect.ValueOf(slice)
	for _i := 0; _i < sliceValue.Len(); _i++ {
		it := sliceValue.Index(_i).Interface()
		_f(it)
	}
}

func (g *GetHistoricalOrdersRequest) isVarSlice(_v interface{}) bool {
	rt := reflect.TypeOf(_v)
	switch rt.Kind() {
	case reflect.Slice:
		return true
	}
	return false
}

func (g *GetHistoricalOrdersRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := g.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for _k, _v := range params {
		slugs[_k] = fmt.Sprintf("%v", _v)
	}

	return slugs, nil
}

// GetPath returns the request path of the API
func (g *GetHistoricalOrdersRequest) GetPath() string {
	return "/info"
}

// Do generates the request object and send the request object to the API endpoint
func (g *GetHistoricalOrdersRequest) Do(ctx context.Context) ([]HistoricalOrdersResponse, error) {

	params, err := g.GetParameters()
	if err != nil {
		return nil, err
	}
	query := url.Values{}

	var apiURL string

	apiURL = g.GetPath()

	req, err := g.client.NewRequest(ctx, "POST", apiURL, query, params)
	if err != nil {
		return nil, err
	}

	response, err := g.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse APIResponse

	type responseUnmarshaler interface {
		Unmarshal(data []byte) error
	}

	if unmarshaler, ok := interface{}(&apiResponse).(responseUnmarshaler); ok {
		if err := unmarshaler.Unmarshal(response.Body); err != nil {
			return nil, err
		}
	} else {
		// The line below checks the content type, however, some API server might not send the correct content type header,
		// Hence, this is commented for backward compatibility
		// response.IsJSON()
		if err := response.DecodeJSON(&apiResponse); err != nil {
			return nil, err
		}
	}

	type responseValidator interface {
		Validate() error
	}

	if validator, ok := interface{}(&apiResponse).(responseValidator); ok {
		if err := validator.Validate(); err != nil {
			return nil, err
		}
	}
	var data []HistoricalOrdersResponse
	if err := json.Unmarshal(apiResponse.Response.Data, &data); err != nil {
		return nil, err
	}
	return data, nil
}
