// Code generated by "callbackgen -type FixedWindowVolumeProfile"; DO NOT EDIT.

package indicatorv2

import (
	"github.com/c9s/bbgo/pkg/types"
)

func (vp *FixedWindowVolumeProfile) OnReset(cb func(profile map[float64]float64, accKLine types.KLine)) {
	vp.resetCallbacks = append(vp.resetCallbacks, cb)
}

func (vp *FixedWindowVolumeProfile) EmitReset(profile map[float64]float64, accKLine types.KLine) {
	for _, cb := range vp.resetCallbacks {
		cb(profile, accKLine)
	}
}
