// Code generated by "callbackgen -type FixedWindowVolumeProfile"; DO NOT EDIT.

package indicatorv2

import ()

func (vp *FixedWindowVolumeProfile) OnReset(cb func(profile map[float64]float64)) {
	vp.resetCallbacks = append(vp.resetCallbacks, cb)
}

func (vp *FixedWindowVolumeProfile) EmitReset(profile map[float64]float64) {
	for _, cb := range vp.resetCallbacks {
		cb(profile)
	}
}
