persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
#    futures: true

exchangeStrategies:
- on: binance
  audacitymaker:
    symbol: ETHBUSD
    orderFlow:
      interval: 1m
      quantity: 0.01
