# usage:
#
#   go run ./cmd/bbgo optimize --config bollmaker_ethusdt.yaml  --optimizer-config optimizer.yaml --debug
#
---
executor:
  type: local
  local:
    maxNumberOfProcesses: 10

matrix:
- type: iterate
  label: interval
  path: '/exchangeStrategies/0/bollmaker/interval'
  values: [ "1m", "5m", "15m", "30m" ]

- type: range
  path: '/exchangeStrategies/0/bollmaker/amount'
  label: amount
  min: 20.0
  max: 100.0
  step: 20.0

- type: range
  label: spread
  path: '/exchangeStrategies/0/bollmaker/spread'
  min: 0.1%
  max: 0.2%
  step: 0.01%
