---
sessions:
  binance:
    exchange: binance
    futures: true
    envVarPrefix: binance
    heikinAshi: false

exchangeStrategies:
 
- on: binance
  ewo_dgtrd:
    symbol: MATICUSDT
    # kline interval for indicators
    interval: 15m
    # use ema as MA
    useEma: false
    # use sma as MA, used when ema is false
    # if both sma and ema are false, use EVMA
    useSma: false
    # ewo signal line window size
    sigWin: 5
    # SL percentage from entry price
    stoploss: 2%
    # use HeikinAshi klines instead of normal OHLC
    useHeikinAshi: true
    # disable SL when short
    disableShortStop: false
    # disable SL when long
    disableLongStop: false
    # CCI Stochastic Indicator high filter
    cciStochFilterHigh: 80
    # CCI Stochastic Indicator low filter
    cciStochFilterLow: 20
    # ewo change rate histogram's upperbound filter
    # set to 1 would intend to let all ewo pass
    ewoChangeFilterHigh: 1.
    # ewo change rate histogram's lowerbound filter
    # set to 0 would intend to let all ewo pass
    ewoChangeFilterLow: 0.0
    # print record exit point in log messages
    record: false

sync:
  userDataStream:
    trades: true
    filledOrders: true
  sessions:
    - binance
  symbols:
    - MATICUSDT

backtest:
  startTime: "2022-05-01"
  endTime: "2022-05-27"
  symbols:
    - MATICUSDT
  sessions: [binance]
  accounts:
    binance:
      #makerFeeRate: 0
      #takerFeeRate: 15
      balances:
        MATIC: 000.0
        USDT: 15000.0
