persistence:
json:
  directory: var/data
redis:
  host: 127.0.0.1
  port: 6379
  db: 0

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

exchangeStrategies:
  - on: binance
    harmonic:
      symbol: BTCBUSD
      interval: 1s
      window: 60
      quantity: 0.005
      # Draw pnl
      drawGraph: true
      graphPNLPath: "./pnl.png"
      graphCumPNLPath: "./cumpnl.png"

backtest:
  sessions:
    - binance
  startTime: "2022-10-01"
  endTime: "2022-10-07"
  symbols:
    - BTCBUSD
  accounts:
    binance:
      balances:
        BTC: 1.0
        BUSD: 60_000.0