---
sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

  #max:
  #  exchange: max
  #  envVarPrefix: max

riskControls:
  # This is the session-based risk controller, which let you configure different risk controller by session.
  sessionBased:
    # "max" is the session name that you want to configure the risk control
    max:
      # orderExecutor is one of the risk control
      orderExecutor:
        # symbol-routed order executor
        bySymbol:
          ETHUSDT:
            # basic risk control order executor
            basic:
              minQuoteBalance: 10.0
              maxBaseAssetBalance: 3.0
              minBaseAssetBalance: 0.0
              maxOrderAmount: 1000.0

# example command:
#    godotenv -f .env.local -- go run ./cmd/bbgo backtest --sync-from 2020-11-01 --config config/grid.yaml --base-asset-baseline
backtest:
  startTime: "2022-06-01"
  endTime: "2022-06-17"
  symbols:
    - ETHUSDT
  sessions: [binance]
  accounts:
    binance:
      balances:
        ETH: 0
        USDT: 5000.0

exchangeStrategies:

#- on: binance
  #grid:
    #symbol: BTCUSDT
    ##quantity: 0.001
    ##amount: 50
    #quantityScale:
      #byPrice:
        #exp:
          #domain: [20_000, 70_000]
          #range: [0.001, 0.0007]
    #gridNumber: 33 # 33: spread = 1785
    #profitSpread: 2000.0  # The profit price spread that you want to add to your sell order when your buy order is executed
    #upperPrice: 70_000.0
    #lowerPrice: 20_000.0
    #long: true  # The sell order is submitted in the same order amount as the filled corresponding buy order, rather than the same quantity.
- on: binance
  infinity-grid:
    symbol: ETHUSDT
    interval: 1m
    quantity: 0.05
    initialOrderQuantity: 1
    gridNumber: 10
    countOfMoreOrders: 3 # +2
    margin: 0.030
    lowerPrice: 700
    long: true
