persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
  max:
    exchange: max
    envVarPrefix:  max
  ftx:
    exchange: ftx
    envVarPrefix: ftx

exchangeStrategies:
- on: binance
  irr:
    symbol: BTCBUSD
    # in milliseconds(ms)
    # must > 10 ms
    hftInterval: 1000
    # qty per trade
    quantity: 0.001
    # Draw pnl
    drawGraph: true
    graphPNLPath: "./pnl.png"
    graphCumPNLPath: "./cumpnl.png"
