persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
  max:
    exchange: max
    envVarPrefix:  max
  ftx:
    exchange: ftx
    envVarPrefix: ftx

exchangeStrategies:
- on: binance
  irr:
    symbol: BTCBUSD
    # in milliseconds(ms)
    hftInterval: 1000
    # indicator window
    window: 0
    # maxima position in USD
    amount: 100
    quantity: 0.001
    # minProfit pips in USD
    pips: 0.0
    # alpha1: negative return reversion
    NR: true
    # alpha2: moving average reversion
    MR: true
    # Draw pnl
    drawGraph: true
    graphPNLPath: "./pnl.png"
    graphCumPNLPath: "./cumpnl.png"
