persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

exchangeStrategies:
- on: binance
  irr:
    symbol: BTCBUSD
    # in milliseconds(ms)
    hftInterval: 5
    # indicator window
    window: 100
    # limit maker order quantity
    quantity: 0.01
    # bonus spread in USD
    spread: 0.25
    # alpha1: negative return reversion
    NR: true
    # alpha2: moving average reversion
    MR: true
    # Draw pnl
    drawGraph: true
    graphPNLPath: "./pnl.png"
    graphCumPNLPath: "./cumpnl.png"
