sessions:
  binance:
    exchange: binance
    envVarPrefix: binance
#    futures: true


exchangeStrategies:
- on: binance
  pivot:
    symbol: BTCBUSD
    interval: 1h
    quantity: 0.95
    stopLossRatio: 0.8%
    catBounceRatio: 3%
    shadowTPRatio: 2.5%

backtest:
  sessions:
    - binance
  # for testing max draw down (MDD) at 03-12
  # see here for more details
  # https://www.investopedia.com/terms/m/maximum-drawdown-mdd.asp
  startTime: "2022-01-01"
  endTime: "2022-05-10"
  symbols:
    - BTCBUSD
  account:
    binance:
      balances:
        BTC: 1.0
        BUSD: 1_000.0
