---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"

  # if you want to route channel by symbol
  symbolChannels:
    "^BTC": "btc"
    "^ETH": "eth"

  # object routing rules
  routing:
    trade: "$symbol"
    order: "$symbol"
    submitOrder: "$session" # not supported yet
    pnL: "bbgo-pnl"

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

exchangeStrategies:
- on: binance
  pricealert:
    symbol: "BTCUSDT"
    interval: "1m"
    minChange: 0.01
