---
sessions:
  binance:
    exchange: binance
    heikinAshi: true
    envVarPrefix: binance

exchangeStrategies:
 
- on: binance
  skeleton:
    symbol: BNBBUSD

backtest:
  startTime: "2022-06-14"
  endTime: "2022-06-15"
  symbols:
    - BNBBUSD
  sessions: [binance]
  account:
    binance:
      balances:
        BNB: 0
        BUSD: 10000
