---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"

  switches:
    trade: true
    orderUpdate: true
    submitOrder: true

sessions:
  binance:
    exchange: binance
    envVarPrefix: binance

riskControls:
  # This is the session-based risk controller, which let you configure different risk controller by session.
  sessionBased:
    # "max" is the session name that you want to configure the risk control
    binance:
      # orderExecutor is one of the risk control
      orderExecutor:
        # symbol-routed order executor
        bySymbol:
          BNBUSDT:
            # basic risk control order executor
            basic:
              minQuoteBalance: 1000.0
              maxBaseAssetBalance: 50.0
              minBaseAssetBalance: 10.0
              maxOrderAmount: 100.0

exchangeStrategies:
- on: binance
  swing:
    symbol: BNBUSDT
    interval: 1m
    minChange: 0.01
    baseQuantity: 1.0
    movingAverageType: EWMA
    movingAverageInterval: 1m
    movingAverageWindow: 99
