---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"

  switches:
    trade: true
    orderUpdate: false
    submitOrder: false

persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

logging:
  trade: true
  order: true
  fields:
    env: local

sessions:
  max:
    exchange: max
    envVarPrefix: max

  binance:
    exchange: binance
    envVarPrefix: binance

crossExchangeStrategies:

- xmaker:
    symbol: "BTCUSDT"
    sourceExchange: binance
    makerExchange: max
    updateInterval: 1s

    # disableHedge disables the hedge orders on the source exchange
    # disableHedge: true

    hedgeInterval: 10s
    notifyTrade: true

    margin: 0.004
    askMargin: 0.4%
    bidMargin: 0.4%

    quantity: 0.001
    quantityMultiplier: 2

    # numLayers means how many order we want to place on each side. 3 means we want 3 bid orders and 3 ask orders
    numLayers: 1
    # pips is the fraction numbers between each order. for BTC, 1 pip is 0.1,
    # 0.1 pip is 0.01, here we use 10, so we will get 18000.00, 18001.00 and
    # 18002.00
    pips: 10
    ## profitFixer is used for fixing the profit stats and the position
    # profitFixer:
    #   tradesSince: "2024-08-01T15:00:00.000+08:00"
    circuitBreaker:
      enabled: true
      maximumConsecutiveTotalLoss: 36.0
      maximumConsecutiveLossTimes: 10
      maximumLossPerRound: 15.0
      maximumTotalLoss: 80.0
      ignoreConsecutiveDustLoss: true
      consecutiveDustLossThreshold: 0.003
      haltDuration: "30m"
      maximumHaltTimes: 2
      maximumHaltTimesExceededPanic: true
