---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"

  switches:
    trade: true
    orderUpdate: false
    submitOrder: false

persistence:
  json:
    directory: var/data
  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

sessions:
  max:
    exchange: max
    envVarPrefix: max

  binance:
    exchange: binance
    envVarPrefix: binance

riskControls:
  # This is the session-based risk controller, which let you configure different risk controller by session.
  sessionBased:
    # "max" is the session name that you want to configure the risk control
    max:
      # orderExecutor is one of the risk control
      orderExecutor:
        # symbol-routed order executor
        bySymbol:
          ETHUSDT:
            # basic risk control order executor
            basic:
              # keep at least X USDT (keep cash)
              minQuoteBalance: 100.0

              # maximum ETH balance (don't buy too much)
              maxBaseAssetBalance: 10.0

              # minimum ETH balance (don't sell too much)
              minBaseAssetBalance: 0.0

              maxOrderAmount: 1000.0

crossExchangeStrategies:

- xmaker:
    symbol: ETHUSDT
    sourceExchange: binance
    makerExchange: max
    updateInterval: 2s

    # disableHedge disables the hedge orders on the source exchange
    # disableHedge: true

    hedgeInterval: 10s

    margin: 0.004
    askMargin: 0.004
    bidMargin: 0.004

    quantity: 0.01
    quantityMultiplier: 2

    # numLayers means how many order we want to place on each side. 3 means we want 3 bid orders and 3 ask orders
    numLayers: 2

    # pips is the fraction numbers between each order. for BTC, 1 pip is 0.1,
    # 0.1 pip is 0.01, here we use 10, so we will get 18000.00, 18001.00 and
    # 18002.00
    pips: 10

    persistence:
      type: redis

