---
notifications:
  slack:
    defaultChannel: "dev-bbgo"
    errorChannel: "bbgo-error"
  switches:
    trade: true
    orderUpdate: true
    submitOrder: true

sessions:
  binance:
    exchange: binance

backtest:
  startTime: "2021-09-01"
  endTime: "2021-11-01"
  sessions:
  - binance
  symbols:
  - BTCUSDT
  account:
    binance:
      balances:
        USDT: 10000.0

exchangeStrategies:

- on: binance
  support:
    symbol: BTCUSDT
    # quantity: 0.1
    scaleQuantity:
      byVolume:
        exp:
          domain: [ 10_000, 200_000 ]
          range: [ 0.5, 1.0 ]
    maxExposure: 0.5
    volumeInterval: 15m
    volumeThreshold: 800
    volumeThresholdInQuote: 40_000
    minKLineLowerShadowRatio: 0.3
    engulfingInterval: 30m
    emaWindow:
      interval: 15m
      window: 120
