// Code generated by "callbackgen -type ConnectivityGroup"; DO NOT EDIT.

package types

import ()

func (g *ConnectivityGroup) OnConnect(cb func()) {
	g.connectCallbacks = append(g.connectCallbacks, cb)
}

func (g *ConnectivityGroup) EmitConnect() {
	for _, cb := range g.connectCallbacks {
		cb()
	}
}

func (g *ConnectivityGroup) OnDisconnect(cb func()) {
	g.disconnectCallbacks = append(g.disconnectCallbacks, cb)
}

func (g *ConnectivityGroup) EmitDisconnect() {
	for _, cb := range g.disconnectCallbacks {
		cb()
	}
}

func (g *ConnectivityGroup) OnAuth(cb func()) {
	g.authCallbacks = append(g.authCallbacks, cb)
}

func (g *ConnectivityGroup) EmitAuth() {
	for _, cb := range g.authCallbacks {
		cb()
	}
}
