// Code generated by "callbackgen -type RBTOrderBook"; DO NOT EDIT.

package types

import ()

func (b *RBTOrderBook) OnLoad(cb func(book *RBTOrderBook)) {
	b.loadCallbacks = append(b.loadCallbacks, cb)
}

func (b *RBTOrderBook) EmitLoad(book *RBTOrderBook) {
	for _, cb := range b.loadCallbacks {
		cb(book)
	}
}

func (b *RBTOrderBook) OnUpdate(cb func(book *RBTOrderBook)) {
	b.updateCallbacks = append(b.updateCallbacks, cb)
}

func (b *RBTOrderBook) EmitUpdate(book *RBTOrderBook) {
	for _, cb := range b.updateCallbacks {
		cb(book)
	}
}
