// Code generated by "callbackgen -type SkipListOrderBook"; DO NOT EDIT.

package types

import ()

func (b *SkipListOrderBook) OnLoad(cb func(book *SkipListOrderBook)) {
	b.loadCallbacks = append(b.loadCallbacks, cb)
}

func (b *SkipListOrderBook) EmitLoad(book *SkipListOrderBook) {
	for _, cb := range b.loadCallbacks {
		cb(book)
	}
}

func (b *SkipListOrderBook) OnUpdate(cb func(book *SkipListOrderBook)) {
	b.updateCallbacks = append(b.updateCallbacks, cb)
}

func (b *SkipListOrderBook) EmitUpdate(book *SkipListOrderBook) {
	for _, cb := range b.updateCallbacks {
		cb(book)
	}
}
