// Code generated by "callbackgen -type SliceOrderBook"; DO NOT EDIT.

package types

import ()

func (b *SliceOrderBook) OnLoad(cb func(book *SliceOrderBook)) {
	b.loadCallbacks = append(b.loadCallbacks, cb)
}

func (b *SliceOrderBook) EmitLoad(book *SliceOrderBook) {
	for _, cb := range b.loadCallbacks {
		cb(book)
	}
}

func (b *SliceOrderBook) OnUpdate(cb func(book *SliceOrderBook)) {
	b.updateCallbacks = append(b.updateCallbacks, cb)
}

func (b *SliceOrderBook) EmitUpdate(book *SliceOrderBook) {
	for _, cb := range b.updateCallbacks {
		cb(book)
	}
}
