// Code generated by "callbackgen -type StreamOrderBook"; DO NOT EDIT.

package types

import ()

func (sb *StreamOrderBook) OnUpdate(cb func(update SliceOrderBook)) {
	sb.updateCallbacks = append(sb.updateCallbacks, cb)
}

func (sb *StreamOrderBook) EmitUpdate(update SliceOrderBook) {
	for _, cb := range sb.updateCallbacks {
		cb(update)
	}
}

func (sb *StreamOrderBook) OnSnapshot(cb func(snapshot SliceOrderBook)) {
	sb.snapshotCallbacks = append(sb.snapshotCallbacks, cb)
}

func (sb *StreamOrderBook) EmitSnapshot(snapshot SliceOrderBook) {
	for _, cb := range sb.snapshotCallbacks {
		cb(snapshot)
	}
}
