// Code generated by "callbackgen -type KLineStore"; DO NOT EDIT.

package store

import (
	"github.com/c9s/bbgo/pkg/types"
)

func (store *KLineStore) OnUpdate(cb func(kline types.KLine)) {
	store.updateCallbacks = append(store.updateCallbacks, cb)
}

func (store *KLineStore) EmitUpdate(kline types.KLine) {
	for _, cb := range store.updateCallbacks {
		cb(kline)
	}
}
