// Code generated by "requestgen -type GetMovementHistoryRequest -method POST -url /v2/auth/r/movements/:currency/hist -responseType []Movement"; DO NOT EDIT.

package bfxapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"reflect"
	"regexp"
	"time"
)

/*
 * Start sets
 */
func (g *GetMovementHistoryRequest) Start(start time.Time) *GetMovementHistoryRequest {
	g.start = &start
	return g
}

/*
 * End sets
 */
func (g *GetMovementHistoryRequest) End(end time.Time) *GetMovementHistoryRequest {
	g.end = &end
	return g
}

/*
 * Limit sets
 */
func (g *GetMovementHistoryRequest) Limit(limit int) *GetMovementHistoryRequest {
	g.limit = &limit
	return g
}

/*
 * Id sets
 */
func (g *GetMovementHistoryRequest) Id(id []int64) *GetMovementHistoryRequest {
	g.id = id
	return g
}

func (g *GetMovementHistoryRequest) AddId(id ...int64) *GetMovementHistoryRequest {
	g.id = append(g.id, id...)
	return g
}

/*
 * Address sets
 */
func (g *GetMovementHistoryRequest) Address(address string) *GetMovementHistoryRequest {
	g.address = &address
	return g
}

/*
 * Currency sets
 */
func (g *GetMovementHistoryRequest) Currency(currency string) *GetMovementHistoryRequest {
	g.currency = currency
	return g
}

// GetQueryParameters builds and checks the query parameters and returns url.Values
func (g *GetMovementHistoryRequest) GetQueryParameters() (url.Values, error) {
	var params = map[string]interface{}{}

	query := url.Values{}
	for _k, _v := range params {
		if g.isVarSlice(_v) {
			g.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParameters builds and checks the parameters and return the result in a map object
func (g *GetMovementHistoryRequest) GetParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check start field -> json key start
	if g.start != nil {
		start := *g.start

		// TEMPLATE check-required

		if start.IsZero() {
		}
		// END TEMPLATE check-required

		// assign parameter of start
		params["start"] = start
	} else {
	}
	// check end field -> json key end
	if g.end != nil {
		end := *g.end

		// TEMPLATE check-required

		if end.IsZero() {
		}
		// END TEMPLATE check-required

		// assign parameter of end
		params["end"] = end
	} else {
	}
	// check limit field -> json key limit
	if g.limit != nil {
		limit := *g.limit

		// TEMPLATE check-required

		if limit == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of limit
		params["limit"] = limit
	} else {
	}
	// check id field -> json key id
	id := g.id

	// TEMPLATE check-required
	// END TEMPLATE check-required

	// assign parameter of id
	if len(id) > 0 {
		params["id"] = id
	}
	// check address field -> json key address
	if g.address != nil {
		address := *g.address

		// TEMPLATE check-required
		if len(address) == 0 {
		}
		// END TEMPLATE check-required

		// assign parameter of address
		params["address"] = address
	} else {
	}

	return params, nil
}

// GetParametersQuery converts the parameters from GetParameters into the url.Values format
func (g *GetMovementHistoryRequest) GetParametersQuery() (url.Values, error) {
	query := url.Values{}

	params, err := g.GetParameters()
	if err != nil {
		return query, err
	}

	for _k, _v := range params {
		if g.isVarSlice(_v) {
			g.iterateSlice(_v, func(it interface{}) {
				query.Add(_k+"[]", fmt.Sprintf("%v", it))
			})
		} else {
			query.Add(_k, fmt.Sprintf("%v", _v))
		}
	}

	return query, nil
}

// GetParametersJSON converts the parameters from GetParameters into the JSON format
func (g *GetMovementHistoryRequest) GetParametersJSON() ([]byte, error) {
	params, err := g.GetParameters()
	if err != nil {
		return nil, err
	}

	return json.Marshal(params)
}

// GetSlugParameters builds and checks the slug parameters and return the result in a map object
func (g *GetMovementHistoryRequest) GetSlugParameters() (map[string]interface{}, error) {
	var params = map[string]interface{}{}
	// check currency field -> json key currency
	currency := g.currency

	// TEMPLATE check-required
	if len(currency) == 0 {
	}
	// END TEMPLATE check-required

	// assign parameter of currency
	params["currency"] = currency

	return params, nil
}

func (g *GetMovementHistoryRequest) applySlugsToUrl(url string, slugs map[string]string) string {
	for _k, _v := range slugs {
		needleRE := regexp.MustCompile(":" + _k + "\\b")
		url = needleRE.ReplaceAllString(url, _v)
	}

	return url
}

func (g *GetMovementHistoryRequest) iterateSlice(slice interface{}, _f func(it interface{})) {
	sliceValue := reflect.ValueOf(slice)
	for _i := 0; _i < sliceValue.Len(); _i++ {
		it := sliceValue.Index(_i).Interface()
		_f(it)
	}
}

func (g *GetMovementHistoryRequest) isVarSlice(_v interface{}) bool {
	rt := reflect.TypeOf(_v)
	switch rt.Kind() {
	case reflect.Slice:
		return true
	}
	return false
}

func (g *GetMovementHistoryRequest) GetSlugsMap() (map[string]string, error) {
	slugs := map[string]string{}
	params, err := g.GetSlugParameters()
	if err != nil {
		return slugs, nil
	}

	for _k, _v := range params {
		slugs[_k] = fmt.Sprintf("%v", _v)
	}

	return slugs, nil
}

// GetPath returns the request path of the API
func (g *GetMovementHistoryRequest) GetPath() string {
	return "/v2/auth/r/movements/:currency/hist"
}

// Do generates the request object and send the request object to the API endpoint
func (g *GetMovementHistoryRequest) Do(ctx context.Context) ([]Movement, error) {

	params, err := g.GetParameters()
	if err != nil {
		return nil, err
	}
	query := url.Values{}

	var apiURL string

	apiURL = g.GetPath()
	slugs, err := g.GetSlugsMap()
	if err != nil {
		return nil, err
	}

	apiURL = g.applySlugsToUrl(apiURL, slugs)

	req, err := g.client.NewAuthenticatedRequest(ctx, "POST", apiURL, query, params)
	if err != nil {
		return nil, err
	}

	response, err := g.client.SendRequest(req)
	if err != nil {
		return nil, err
	}

	var apiResponse []Movement

	type responseUnmarshaler interface {
		Unmarshal(data []byte) error
	}

	if unmarshaler, ok := interface{}(&apiResponse).(responseUnmarshaler); ok {
		if err := unmarshaler.Unmarshal(response.Body); err != nil {
			return nil, err
		}
	} else {
		// The line below checks the content type, however, some API server might not send the correct content type header,
		// Hence, this is commented for backward compatibility
		// response.IsJSON()
		if err := response.DecodeJSON(&apiResponse); err != nil {
			return nil, err
		}
	}

	type responseValidator interface {
		Validate() error
	}

	if validator, ok := interface{}(&apiResponse).(responseValidator); ok {
		if err := validator.Validate(); err != nil {
			return nil, err
		}
	}
	return apiResponse, nil
}
