// Code generated by "callbackgen -type LSBAR"; DO NOT EDIT.

package factorzoo

import ()

func (inc *LSBAR) OnUpdate(cb func(val float64)) {
	inc.UpdateCallbacks = append(inc.UpdateCallbacks, cb)
}

func (inc *LSBAR) EmitUpdate(val float64) {
	for _, cb := range inc.UpdateCallbacks {
		cb(val)
	}
}
